version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_control-finance
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
